### ISSUE TITLE
Automatically add/string tag prefix from tool versions.

### ISSUE THREAD

**Issue by RichiCoder1** [yokawasa/action-setup-kube-tools#13]
I'm using Renovate Bot's regex feature to automatically keep tool versions up to day, but one early issue I ran into is by default renovate wants to include the `v` prefix which causes issues with this action's prefixing behavior. It'd be great if it'd automatically add/remove the prefix as necessary.

**Comment by RichiCoder1** [comment]
For some context on what I'm doing:
```
  # Should match current clusters lowest available version
  KUBE_VERSION: "1.17.4"
  # renovate: datasource=github-tags depName=kubernetes-sigs/kustomize
  KUSTOMIZE_VERSION: "3.5.4"
  # renovate: datasource=github-tags depName=helm/helm
  HELM_VERSION: "3.5.3"
  # renovate: datasource=github-tags depName=instrumenta/kubeval
  KUBEVAL_VERSION: "0.16.1"
  # renovate: datasource=github-tags depName=open-policy-agent/conftest
  CONFTEST_VERSION: "0.22.0"
```
I current have renovate stripping the leading `v`, but it'd be nice to have the action do that by default.

**Comment by yokawasa** [comment]
@RichiCoder1  (very sorry for the late response. I was completely occupied for the last 2 weeks)
Thank you for the issue! 
Do you mean that the action automatically strip prefix 'v' if each tool version string include prefix 'v' in it?

```yaml
    - uses: yokawasa/action-setup-kube-tools@v0.6.0
      with:
        kubectl: 'v1.17.1'
        kustomize: 'v3.7.0'
        helm: 'v2.16.7'
        helmv3: 'v3.2.4'
        kubeval: 'v0.14.0'
        conftest: 'v0.18.2'
        rancher: 'v2.4.10'
        tilt: 'v0.18.11'
        skaffold: 'v1.20.0'
        kube-score: 'v1.10.1'
```
