### ISSUE TITLE
Is there a way to specify ARCH type for pulling the right binaries for the setup tools

### ISSUE THREAD

**Issue by 00r2** [yokawasa/action-setup-kube-tools#47]
I am using this action quite often and recently we adopted ARM based runners and the setup tools is failing to pull the arm based binaries. Is there anyway to provide an input to select architecture type  like (`amd64` or `arm64`) etc?

**Comment by yokawasa** [comment]
@00r2 thank you for your opening issue and I'm very sorrry for the late response.

I think  I can add new `arch-type` parameter like this below.  would it work for you?

Suppose that new input parameter named arch-type ('amd64' by default) is added
Sample workflow would be like this
```
  test: 
    steps:
    - uses: actions/checkout@v4
    - uses: yokawasa/action-setup-kube-tools@v0.10.0
      with:
        arch-type: 'arm64'
        setup-tools: |
          kubectl
        kubectl: '1.25'
    - run: |
        kubectl version --client
```
