### ISSUE TITLE
[FEATURE] add k8s CD tools

### ISSUE THREAD

**Issue by Raboo** [yokawasa/action-setup-kube-tools#5]
Hi,

I have a feature request.
I wonder if it's possible to add CD tools for Kubernetes like [Tilt](https://tilt.dev) and [Skaffold](https://skaffold.dev)?

Releases can be found here.
https://github.com/tilt-dev/tilt/releases
https://github.com/GoogleContainerTools/skaffold/releases

In order to reduce footprint it would also be nice if they were made them optional.
Where this would not install the binaries.
```yaml
    - uses: yokawasa/action-setup-kube-tools@v0.3.0
      with:
        tilt: null
        skaffold: null
```

And  this would install them.
```yaml
    - uses: yokawasa/action-setup-kube-tools@v0.3.0
      with:
        tilt: '0.18.11'
        skaffold: '1.20.0'
```

A side benefit of this is also that there is no need to track external versions in this project, simply default to null and only install them when the user sets the version.
