### ISSUE TITLE
Feature: add download option to choose which tool to download

### ISSUE THREAD

**Issue by yokawasa** [yokawasa/action-setup-kube-tools#8]
Currently the actions download all tools
By disabling download option for a specific tool, you can choose not to download the tool. The option is enabled by default

**Comment by yokawasa** [comment]
The option would be like this
```yaml
    - uses: yokawasa/action-setup-kube-tools@v0.5.0
      with: 
        setup-tools: |
           kubectl
           kustomize
           skaffold
           kube-score
        kubectl: '1.17.1'
        kustomize: '3.7.0'
        skaffold: '1.20.0'
        kube-score: '1.10.1'
      id: setup

```
